Feature/solid
DmitryTumanov/DTumnovItra pull request #26
Opened 2016-11-08 10:40 UTC by DmitryTumanov

Some of code refactor using solid principles

2016-11-08 10:46 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Data/Repository/Implementations/MsSQLProductRepository.cs
> +                if (time != null)
How about invert this if?

2016-11-08 10:46 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Data/Repository/Implementations/MsSQLProductRepository.cs
> +            using (var db = new OnlinerProducts())
Dont like new statement for implementations. Lets create facroty for contexts or simple injection.

2016-11-09 05:44 UTC, andrei-piatrou requested changes

2016-11-09 05:44 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Data/Repository/Implementations/MsSQLRepository.cs
> +                return "";
string.Empty?

2016-11-09 08:55 UTC, andrei-piatrou requested changes

2016-11-09 08:55 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ConfigChange/IConfigChanger.cs
> +        void TechnologySwap(string newValue);
Not clear name.

2016-11-09 08:55 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ConfigChange/IConfigChanger.cs
> +    public interface IConfigChanger
Name is not clear.

2016-11-09 10:57 UTC, andrei-piatrou requested changes

2016-11-09 10:57 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/Search/ProductParser/IProductParser.cs
> +        SearchResult ParseProductsFromRequest(HttpWebResponse webResponse);
FromRequest is easier name. Class name already contains part of it..

2016-11-09 10:57 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/Search/Request/Implementations/OnlinerRequestCreator.cs
> +    public class OnlinerRequestCreator : IRequestCreator
Facroty is common name for this type of classes.

2016-11-09 11:09 UTC, andrei-piatrou approved these changes

2016-11-09 15:00 UTC, andrei-piatrou approved these changes

2016-11-10 07:20 UTC, andrei-piatrou requested changes

2016-11-10 07:20 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Data/Notifications/Technologies/Implementations/NetMqNotificator.cs
> +        private static void SendTcpMessage(string text, string tcpString, string type, string path = null)
This method does a lot.

2016-11-10 07:50 UTC, andrei-piatrou approved these changes

2016-11-10 07:50 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Data/Notifications/Technologies/Implementations/NetMqNotificator.cs
>                  client.Connect(tcpString);
27 and 28 lines can be swapped, can you answer why?

2016-11-10 07:57 UTC, DmitryTumanov commented on OnlinerTask/OnlinerTask.Data/Notifications/Technologies/Implementations/NetMqNotificator.cs
>                  client.Connect(tcpString);
Client doesn`t play any role in creating message, that`s why firstly we can create message and than configure client to send

2016-11-10 07:59 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Data/Notifications/Technologies/Implementations/NetMqNotificator.cs
>                  client.Connect(tcpString);
Correct. so common logic should be grouped. Lets create message and then configure client and send this message.

2016-11-10 08:03 UTC, andrei-piatrou approved these changes

2016-11-10 14:17 UTC, andrei-piatrou requested changes

2016-11-10 14:17 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/Search/Implementations/SearchService.cs
> +            if (string.IsNullOrEmpty(searchRequest?.SearchString) || searchRequest.PageNumber == 0)
possible < 1?

2016-11-11 10:27 UTC, andrei-piatrou requested changes

2016-11-11 10:27 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/Search/Implementations/SearchService.cs
> +            var request = requestCreator.CreateRequest(searchRequest.SearchString + Configurations.OnlinerPageVariable + searchRequest.PageNumber);
Factory?

2016-11-11 10:27 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/Search/Request/Implementations/OnlinerRequestFactory.cs
> +        public HttpWebRequest CreateRequest(string requestString)
Prefer building by parts (endpoint, params) or something.

2016-11-11 10:40 UTC, andrei-piatrou requested changes
Please create tests for this factory.

2016-11-14 11:52 UTC, andrei-piatrou requested changes
Please, add tests.

2016-11-15 08:20 UTC, andrei-piatrou requested changes

2016-11-15 08:20 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.Tests/RequestFactoryTests.cs
> +        static readonly object[] TestDictionaries =
Access modifier id required.

2016-11-15 09:02 UTC, andrei-piatrou approved these changes

2016-11-21 10:44 UTC, AndreiPiatrou approved these changes
Not bad test cases.

2016-11-23 10:21 UTC, andrei-piatrou approved these changes

2016-11-23 10:37 UTC, andrei-piatrou approved these changes

2016-11-23 11:27 UTC, andrei-piatrou approved these changes

2016-11-23 11:29 UTC, andrei-piatrou approved these changes

2016-11-23 11:47 UTC, andrei-piatrou approved these changes

2016-11-28 10:03 UTC, merged