Feature/elastic search
DmitryTumanov/DTumnovItra pull request #27
Opened 2016-11-28 16:53 UTC by DmitryTumanov

Add logs of product to elasticsearch

2016-11-29 07:23 UTC, andrei-piatrou requested changes

2016-11-29 07:23 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/ClientsFabric/IClientsFabric.cs
> +    public interface IClientsFabric
Factory?

2016-11-29 07:23 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/IProductLogger.cs
> +        Task RemoveLog(int productId);
Is this method really need?

2016-11-29 07:23 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/Implementations/OnlinerProductLogger.cs
> +        public async Task LogAdding(int productId, ProductModel productModel)
Names are not so good. Also think about common logging mechanism. On each model type you should not implement another one method.

2016-11-29 07:23 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/Products/Implementations/Manager.cs
> +            await productLogger.LogAdding(productId, result);
Logging should be deferred as much as possible. Try to rethink how logs should be stored.

2016-11-29 09:03 UTC, DmitryTumanov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/IProductLogger.cs
> +        Task RemoveLog(int productId);
I think, it`s unnecessary to have log of product, which has been unchecked(and in this case we will always have logs of products, that interesting to users)

2016-11-29 09:04 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/IProductLogger.cs
> +        Task RemoveLog(int productId);
So lets add another type of logs - product deletion. It is also useful for business to have this kind of info.

2016-11-29 09:05 UTC, DmitryTumanov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/IProductLogger.cs
> +        Task RemoveLog(int productId);
Okey

2016-11-29 10:00 UTC, andrei-piatrou requested changes

2016-11-29 10:00 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.BLL/Services/ElasticSearch/ProductLogger/ClientsFabric/IClientsFactory.cs
>  namespace OnlinerTask.BLL.Services.ElasticSearch.ProductLogger.ClientsFabric
namespace?

2016-12-01 13:02 UTC, andrei-piatrou approved these changes

2016-12-13 16:35 UTC, andrei-piatrou requested changes

2016-12-13 16:35 UTC, AndrPetrov commented on OnlinerTask/OnlinerTask.WEB/Controllers/PersonalController.cs
> +    [WebApiLogAction]
it is easier to add this filter as global filter.

2016-12-16 11:34 UTC, andrei-piatrou approved these changes

2016-12-16 11:36 UTC, merged